###############################################################################
# Copyright (c) 2021, 2024 Eclipse contributors
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0/.
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     Alexander Fedorov - initial API and implementation
#     Matthias Mailänder - adapted for ChemClipse
###############################################################################

name: Continuous Integration
on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.2-eclipse-temurin-17

    steps:
    - name: Checkout ChemClipse
      uses: actions/checkout@v3
    - name: Build with Maven
      run: mvn -f chemclipse/releng/org.eclipse.chemclipse.aggregator/pom.xml -T 1C clean verify --batch-mode --no-transfer-progress
